`timescale 1ns / 1ps

`include "bcd_alu_op_codes.vh"
`include "bcdu_flags.vh"

// ============================================================================
// BCD Unit
// ============================================================================
// Combines controller, register file, complementor, and ALU to implement a
// programmable BCD Unit.  Accepts 16‑bit instructions and produces
// result digit, status flags and ready signal.

module bcdu #(
    parameter NUM_DIGITS = 4,       // Digits per BCD operand
    parameter NUM_REGS   = 4        // Registers in the internal register file
)(
    input wire                        i_clk,    // Clock
    input wire                        i_rst,    // Reset
    input wire                        i_valid,  // Instruction valid
    input wire                 [15:0] i_instr,  // Instruction

    output wire                 [3:0] o_digit,  // Output digit
    output wire [`BCDU_NUM_FLAGS-1:0] o_flags,  // Status flags
    output wire                       o_ready   // Unit ready for next instr
);

    // Control signals from controller
    wire wr_en; // Register-file write enable

    localparam ADDR_WIDTH = $clog2(NUM_REGS); // Register-file address width

    // Register-file address lines
    wire [ADDR_WIDTH-1:0] wr_addr;
    wire [ADDR_WIDTH-1:0] rd_addr_a;
    wire [ADDR_WIDTH-1:0] rd_addr_b;

    // Data busses to/from register file
    wire [NUM_DIGITS*4-1:0] wr_num;
    wire [NUM_DIGITS*4-1:0] rd_num_a;
    wire [NUM_DIGITS*4-1:0] rd_num_b;

    // Register file instance
    reg_file #(
        .REG_WIDTH(NUM_DIGITS * 4),
        .NUM_REGS(NUM_REGS),
        .ADDR_WIDTH(ADDR_WIDTH)
    ) u_reg_file (
        .i_clk(i_clk),
        .i_wr_en(wr_en),
        .i_wr_addr(wr_addr),
        .i_wr_data(wr_num),
        .i_rd_addr_a(rd_addr_a),
        .o_rd_data_a(rd_num_a),
        .i_rd_addr_b(rd_addr_b),
        .o_rd_data_b(rd_num_b)
    );

    // Bypass mux: if a write occurs to a location being read
    wire [NUM_DIGITS*4-1:0] num_a_mux = ((wr_en && (wr_addr == rd_addr_a)) ? wr_num: rd_num_a);
    wire [NUM_DIGITS*4-1:0] num_b_mux = ((wr_en && (wr_addr == rd_addr_b)) ? wr_num: rd_num_b);

    // Optional 9's complement of operand B
    wire [NUM_DIGITS*4-1:0] ncp_num_b;

    // Instantiate 9's complement unit to support subtraction
    bcd_9s_complementor #(
        .NUM_DIGITS(NUM_DIGITS)
    ) u_ncp (
        .i_num(num_b_mux),
        .o_num(ncp_num_b)
    );

    wire ncp_en; // Enable 9's complement

    // Registers holding operands for ALU
    reg  [NUM_DIGITS*4-1:0] r_num_a;
    wire [NUM_DIGITS*4-1:0] n_num_a = num_a_mux;
    reg  [NUM_DIGITS*4-1:0] r_num_b;
    wire [NUM_DIGITS*4-1:0] n_num_b = (ncp_en ? ncp_num_b : num_b_mux);

    wire [`BCD_ALU_OP_CODE_WIDTH-1:0] alu_op_code; // ALU operation from ctrl

    localparam SHIFT_AMT_WIDTH = $clog2(NUM_DIGITS + 1);

    // Shift amounts generated by controller
    wire [SHIFT_AMT_WIDTH-1:0] shl_amt;
    wire [SHIFT_AMT_WIDTH-1:0] shr_amt;

    // Shift digit inputs/outputs
    wire [3:0] shl_digit_in;
    wire [3:0] shr_digit_in;
    wire [3:0] shl_digit_out;
    wire [3:0] shr_digit_out;

    wire op_shl = (alu_op_code == `BCD_ALU_OP_SHL); // Current ALU op is shift-left
    wire op_shr = (alu_op_code == `BCD_ALU_OP_SHR); // Current ALU op is shift-right

    // Output digit register and next value logic
    reg  [3:0] r_digit_out;
    wire [3:0] n_digit_out = (op_shl ? shl_digit_out : (op_shr ? shr_digit_out : 4'hF));

    wire add_cin; // Carry-in from controller

    // Status flags returned by ALU
    wire shl_zero;
    wire shr_zero;
    wire add_zero;
    wire add_cout;
    wire cmp_gt;
    wire cmp_eq;

    // Zero flag depends on current operation
    wire zero  = (op_shl ? shl_zero : (op_shr ? shr_zero : add_zero));
    // Truncated flag = nonzero digit got shifted out
    wire trunc = ~(op_shl ? shr_zero : shl_zero);

    // Status flag register and mask/save controls
    reg  [`BCDU_NUM_FLAGS-1:0] r_flags, n_flags;
    wire [`BCDU_NUM_FLAGS-1:0] flags_mask;
    wire                       flags_save;

    assign o_digit = r_digit_out;
    assign o_flags = r_flags;

    // ALU instance performs BCD arithmetic/shifts/comparison
    bcd_alu #(
        .NUM_DIGITS(NUM_DIGITS),
        .SHIFT_AMT_WIDTH(SHIFT_AMT_WIDTH)
    ) u_alu (
        .i_op_code(alu_op_code),
        .i_shl_amt(shl_amt),
        .i_shr_amt(shr_amt),
        .i_shl_digit(shl_digit_in),
        .i_shr_digit(shr_digit_in),
        .i_add_cin(add_cin),
        .i_num_a(r_num_a),
        .i_num_b(r_num_b),
        .o_num(wr_num),
        .o_shl_digit(shl_digit_out),
        .o_shr_digit(shr_digit_out),
        .o_shl_zero(shl_zero),
        .o_shr_zero(shr_zero),
        .o_add_zero(add_zero),
        .o_add_cout(add_cout),
        .o_cmp_gt(cmp_gt),
        .o_cmp_eq(cmp_eq)
    );

    // Controller instance drives entire datapath
    bcdu_controller #(
        .NUM_DIGITS(NUM_DIGITS),
        .ADDR_WIDTH(ADDR_WIDTH),
        .SHIFT_AMT_WIDTH(SHIFT_AMT_WIDTH)
    ) u_ctrl (
        .i_clk(i_clk),
        .i_rst(i_rst),
        .i_valid(i_valid),
        .i_instr(i_instr),
        .i_digit(n_digit_out),
        .o_wr_en(wr_en),
        .o_wr_addr(wr_addr),
        .o_rd_addr_a(rd_addr_a),
        .o_rd_addr_b(rd_addr_b),
        .o_ncp_en(ncp_en),
        .o_alu_op_code(alu_op_code),
        .o_shl_amt(shl_amt),
        .o_shr_amt(shr_amt),
        .o_shl_digit(shl_digit_in),
        .o_shr_digit(shr_digit_in),
        .o_add_cin(add_cin),
        .o_flags_mask(flags_mask),
        .o_flags_save(flags_save),
        .o_ready(o_ready)
    );

    wire sub = add_cin;

    // Combinational flag update logic
    always @* begin
        n_flags = ({cmp_eq, cmp_gt, add_cout, trunc, zero} & flags_mask);

        if (flags_save) begin
            if      (!sub && r_flags[`BCDU_CF]) n_flags[`BCDU_CF] = 1'b1;
            else if (sub && !r_flags[`BCDU_CF]) n_flags[`BCDU_CF] = 1'b0;
        end
    end

    // Sequential state registers
    always @(posedge i_clk) begin
        if (i_rst) begin
            r_num_a     <= 0;
            r_num_b     <= 0;
            r_digit_out <= 4'hF;
            r_flags     <= 0;
        end else begin
            r_num_a     <= n_num_a;
            r_num_b     <= n_num_b;
            r_digit_out <= n_digit_out;
            r_flags     <= n_flags;
        end
    end

endmodule
